language: php
php:
  - 7.2

before_script:
  - composer self-update
  - composer update --prefer-source --no-interaction

script: phpunit --configuration phpunit.xml.dist

after_script:
- php vendor/bin/php-coveralls -v
